set ::STACK_SIZE 0x2000
set ::DATA_ALIGN_SIZE 4
# set ::PRINTF_USING_UART
# set ::PRINTF_USING_OLED
set ::TEMPORARY_CACHING_HEAP_START 0
set ::TEMPORARY_CACHING_HEAP_SIZE 0
set ::TEMPORARY_CACHING_HEAP_LAST 0
set ::NUM_THREAD_PER_TEAM 1
set ::UNCACHEABLE_MEMORY_REGION sram
set ::CACHEABLE_MEMORY_REGION sram
set ::BIGDATA_MEMORY_REGION sram

